const fish_list = [
  {
    fish_id: 1,
    fish_name: "trout",
    fish_mean_weight_grams: 500,
    fish_mean_length_cm: 70,
    origin_universe: "reality",
    fishing_regions: "north america",
  },
  {
    fish_id: 2,
    fish_name: "goldfish",
    fish_mean_weight_grams: 500,
    fish_mean_length_cm: 70,
    origin_universe: "reality",
    fishing_regions: "north america",
  },
  {
    fish_id: 3,
    fish_name: "salmon",
    fish_mean_weight_grams: 500,
    fish_mean_length_cm: 70,
    origin_universe: "reality",
    fishing_regions: "atlantic ocean",
  },
  {
    fish_id: 4,
    fish_name: "tuna",
    fish_mean_weight_grams: 500,
    fish_mean_length_cm: 70,
    origin_universe: "reality",
    fishing_regions: "atlantic ocean",
  },
  {
    fish_id: 5,
    fish_name: "tilapia",
    fish_mean_weight_grams: 500,
    fish_mean_length_cm: 70,
    origin_universe: "reality",
    fishing_regions: "pacific ocean",
  },
];
